version: "3"
services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    hostname: mysql-server
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=658766@Jzh
      - MYSQL_DATABASE=aws
    volumes:
      - ./.dep/mysql-server/data:/var/lib/mysql
      - ./.dep/mysql-server/conf:/etc/mysql/conf.d

  mysql-edge:
    image: mysql:8.0
    container_name: mysql-edge
    hostname: mysql-edge
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=658766@Jzh
      - MYSQL_DATABASE=aws
    volumes:
      - ./.dep/mysql-edge/data:/var/lib/mysql
      - ./.dep/mysql-edge/conf:/etc/mysql/conf.d
    depends_on:
      - mysql-server

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: "redis-server --requirepass 658766@Jzh"
    volumes:
      - ./.dep/redis/data:/data
