### 用户登录
POST http://localhost:8080/user/login
content-type: application/json

{
    "uid": "659822",
    "password": "123456"
}

### 获取个人信息

GET http://localhost:8080/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NTk4MjIiLCJpYXQiOjE3NDc3MzUyOTUsImV4cCI6MTc0NzgyMTY5NX0.YwbpoZgfzJNUe9ac3SRgsTFU5EvfYOUrXesWG13Ibe4

### 获取用户列表

GET http://localhost:8080/user/list
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NTk4MjIiLCJpYXQiOjE3NDc3MzUyOTUsImV4cCI6MTc0NzgyMTY5NX0.YwbpoZgfzJNUe9ac3SRgsTFU5EvfYOUrXesWG13Ibe4
