spring:
  application:
    name: aws
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aws
    username: root
    password: 658766@Jzh
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  task:
    scheduling:
      pool:
        size: 5

aws:
  name: Agricultural Weighing System
  farmName: XDU FARM
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    validTime: 24
  admin:
    uid: 659811
    password: 123456

mqtt:
  broker:
    url: tcp://127.0.0.1:1883
  username: aws-server
  password: 123456

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    enabled: false