version: "3"
services:
  mysql-edge:
    image: mysql:8.0
    container_name: mysql-edge
    networks:
      aws:
        aliases:
          - mysql-edge
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=658766@Jzh
      - MYSQL_DATABASE=aws
    volumes:
      - ./.dep/mysql-edge/data:/var/lib/mysql
      - ./.dep/mysql-edge/conf:/etc/mysql/conf.d

  emqx1:
    image: emqx:5.8.6
    container_name: emqx1
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      aws:
        aliases:
          - node1.emqx.io
    ports:
      - 1883:1883 # tcp(mqtt)
      - 8083:8083 # ssl
      - 8084:8084 # ws
      - 8883:8883 # wss
      - 18083:18083 # http(dashboard)
      - 5683:5683/udp # coap
      - 61613:61613 # stomp
    volumes:
      - ./.dep/emqx1/data:/opt/emqx/data
  emqx2:
    image: emqx:5.8.6
    container_name: emqx2
    environment:
    - "EMQX_NODE_NAME=emqx@node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      aws:
        aliases:
          - node2.emqx.io
    ports:
      - 2883:1883 # tcp(mqtt)
      # - 8083:8083 # ssl
      # - 8084:8084 # ws
      # - 8883:8883 # wss
      # - 18083:18083 # http(dashboard)
      # - 5683:5683/udp # coap
      # - 61613:61613 # stomp
    volumes:
      - ./.dep/emqx2/data:/opt/emqx/data
  emqx3:
    image: emqx:5.8.6
    container_name: emqx3
    environment:
    - "EMQX_NODE_NAME=emqx@node3.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      aws:
        aliases:
          - node3.emqx.io
    ports:
      - 3883:1883 # tcp(mqtt)
      # - 8083:8083 # ssl
      # - 8084:8084 # ws
      # - 8883:8883 # wss
      # - 18083:18083 # http(dashboard)
      # - 5683:5683/udp # coap
      # - 61613:61613 # stomp
    volumes:
      - ./.dep/emqx3/data:/opt/emqx/data
      
networks:
  aws:
    external: true