@startwbs
* 农业果实称重云端软件工作分解结构图

** 称重模块
*** 电子秤查询
*** 电子秤管理
*** 称重记录处理
*** 称重记录查询
*** 称重记录统计分析
*** 待办记录查询
*** 待办记录处理

** 用户模块
*** 用户认证
*** 用户授权
*** 用户管理

** 果实模块
*** 果实查询
*** 果实管理
*** 果实图像识别

** 作业模块
*** 采摘工作查询
*** 采摘工作管理


@endwbs
