@startwbs
* 农业果实称重云端软件工作分解结构图

** 用户模块
*** 用户功能
**** 用户认证
**** 个人信息管理
*** 管理员功能
**** 用户信息管理

** 果实模块
*** 果实管理
**** 果实信息维护
**** 果实查询
*** 果实统计
**** 年产量统计
**** 分批产量统计

** 工作服务模块
*** 工作管理
**** 采摘工作维护
**** 采摘工作查询
*** 工作分配
**** 作业分配管理
**** 个人作业查询

** 称重服务模块
*** 电子秤管理
**** 电子秤信息维护
**** 电子秤查询
*** 称重记录
**** 记录管理
*** 统计分析
**** 员工作业统计

@endwbs
