@startmindmap 系统接口设计
* 系统接口设计
    * 称重服务模块
        * 提交称重信息
        * 获取本次称重结果
        * 提交电子秤状态
    * 员工个人模块
        * 个人信息管理
            * 验证个人信息
            * 修改个人信息
            * 获取产出信息
        * 农场信息获取
            * 获取农场信息
            * 获取待采摘果实信息
    * 农场管理模块
        * 员工管理
            * 新增员工
            * 删除员工
            * 修改员工信息
            * 获取员工信息
            * 获取员工产出信息
        * 农场管理
            * 获取农场信息
            * 修改农场信息
        * 电子秤管理
            * 新增电子秤
            * 删除电子秤
            * 修改电子秤信息
            * 获取电子秤信息
        * 采摘管理
            * 新增果实采摘计划
            * 删除果实采摘计划
            * 修改果实采摘计划
            * 获取果实采摘计划
    * 数据可视化模块
        * 果实采摘统计信息
            * 获取图表渲染数据
            * 导出数据报表
        * 员工采摘统计信息
            * 获取图表渲染数据
            * 导出数据报表
@endmindmap