@startuml 核心功能用例图
left to right direction
actor "采摘员工" as staff
actor "农场管理员" as admin
actor "电子秤终端" as terminal

rectangle 农业果实称重云端软件 {
    (称重服务) as uc1

    (用户服务) as uc2
    (个人信息管理) as uc2_a
    (农场信息获取) as uc2_b
    uc2_a .up.> uc2 : <<include>>
    uc2_b .up.> uc2 : <<include>>

    (农场管理) as uc3
    (员工管理) as uc3_a
    (农场管理) as uc3_b
    (电子秤管理) as uc3_c
    (采摘管理) as uc3_d
    uc3_a .up.> uc3 : <<include>>
    uc3_b .up.> uc3 : <<include>>
    uc3_c .up.> uc3 : <<include>>
    uc3_d .up.> uc3 : <<include>>
    
    (数据可视化) as uc4
    (果实采摘统计信息) as uc4_a
    (员工采摘统计信息) as uc4_b
    uc4_a .up.> uc4 : <<include>>
    uc4_b .up.> uc4 : <<include>>
}
terminal --> uc1
staff --> uc1
staff --> uc2
staff --> uc4
admin --> uc2
admin --> uc3
admin --> uc4
@enduml
