@startuml

skinparam sequenceMessageAlign center
skinparam defaultFontSize 25

actor 用户 as Client
participant "UserController" as UserController
participant "SecurityFilterChain" as SecurityFilterChain
participant "JwtAuthFilter" as JwtAuthFilter
participant "AuthorizationFilter" as AuthorizationFilter
participant "UserService" as UserService
participant "JwtService" as JwtService

Client -> UserController: 调用 login 接口\n进行登录
UserController -> UserService: 认证用户
UserService -> UserService: 校验用户名和密码
UserService -> JwtService: 生成 Jwt 令牌
JwtService -> UserService: 返回 Jwt 令牌
UserService -> UserController: 用户认证通过，返回 Jwt 令牌
UserController -> Client: 返回 Jwt 令牌
Client -> Client: 存储 Jwt 令牌
Client -> UserController: 携带 Jwt 令牌\n发起请求
UserController -> SecurityFilterChain: 请求经过安全过滤链\n进行处理
SecurityFilterChain -> JwtAuthFilter: 执行 Jwt 认证过滤器\n的过滤方法
JwtAuthFilter -> JwtService: 校验 Jwt 令牌
JwtService -> JwtAuthFilter: 校验通过
JwtAuthFilter -> UserService: 获取用户明细
UserService -> JwtAuthFilter: 返回用户明细
JwtAuthFilter -> JwtAuthFilter: 在请求上下文中\n设置用户明细
JwtAuthFilter -> SecurityFilterChain: 用户认证通过
SecurityFilterChain -> AuthorizationFilter: 校验用户权限
AuthorizationFilter -> AuthorizationFilter: 通过请求上下文中的\n用户角色列表进行权限校验
AuthorizationFilter -> SecurityFilterChain: 用户权限校验通过
SecurityFilterChain -> UserController: 执行请求相关操作
UserController -> Client: 返回请求结果
@enduml