@startuml

skinparam sequenceMessageAlign center
skinparam defaultFontSize 18

' skinparam Diagram {
'   BorderColor black
'   BorderThickness 1
' }

actor 采摘人员 as staff
entity 电子秤 as scale
participant 云端软件 as server
activate staff
activate scale
staff->scale: 放置果实
scale->scale: 读取称重数据
staff->scale: 扫描员工卡
scale->scale: 读取员工卡数据
scale->scale: 拍摄并存储果实图片
scale->scale: 识别果实种类(可选)
activate server
scale->server: 生成并提交称重信息
server->server: 识别果实\n种类(可选)
server->server: 存储称重信息\n或转存为待办
server->scale: 返回提交结果
deactivate server
scale->staff: 显示提交结果
staff->staff: 果实入库
deactivate scale
deactivate staff
@enduml
