@startuml 称重数据处理流程活动图
|tm| 电子秤终端
|sc| 电子秤
|sys| 称重云端系统

|tm|
start
:进入终端系统;
repeat :员工刷卡;
:读取并发送卡信息;
|sys|
backward: 返回报错信息;
repeat while (认证员工) is(失败) not(成功)

|tm|
:显示果实和个人信息;
repeat 
:选择果实种类;
|sc|
:放置果实;
:完成称重并等待读取;
|tm|
:读取称重结果;
:生成并发送称重信息;
|sys| 
:处理称重信息;
:返回称重结果;
|tm|
if (处理结果) then(成功)
    |tm|
    :显示称重完成;
    |sc|
    :果实入库;
else(失败)
    |tm|
    :显示错误信息;
|tm|
endif
|tm|
repeat while(是否结束称重?)
:账号登出，返回主界面;
stop
@enduml