@startuml 核心功能用例图
left to right direction
actor "采摘员工" as staff
actor "农场管理员" as admin
actor "系统管理员" as root
actor "电子秤终端" as terminal

rectangle 农业果实称重云端软件 {
    (登录认证) as uc0

    (查看数据看板) as uc1
    (导出数据报表) as uc1_a
    uc1_a .up.> uc1 : <<include>>

    (员工管理) as uc2
    (添加员工) as uc2_a
    uc2_a .up.> uc2 : <<include>>
    (删除员工) as uc2_b
    uc2_b .up.> uc2 : <<include>>
    (修改员工) as uc2_c
    uc2_c .up.> uc2 : <<include>>

    (农场管理) as uc3
    (注册农场) as uc3_a
    uc3_a .up.> uc3 : <<include>>
    (删除农场) as uc3_b
    uc3_b .up.> uc3 : <<include>>
    (修改农场) as uc3_c
    uc3_c .up.> uc3 : <<include>>

    (电子秤管理) as uc3
    (新增电子秤) as uc3_a
    uc3_a .up.> uc3 : <<include>>
    (删除电子秤) as uc3_b
    uc3_b .up.> uc3 : <<include>>
    (修改电子秤) as uc3_c
    uc3_c .up.> uc3 : <<include>>

    (称重管理) as uc4
    (查看称重记录) as uc4_a
    uc4_a .up.> uc4 : <<include>>
    (导出称重记录) as uc4_b
    uc4_b .up.> uc4 : <<extend>>

    (果实称重) as uc5
    (提交称重结果) as uc5_a
    uc5_a .up.> uc5 : <<include>>
    (查看称重结果) as uc5_b
    uc5_b .up.> uc5 : <<include>>
}
staff --> uc0
admin --> uc0
terminal --> uc0
admin --> uc1
admin --> uc2
admin --> uc3
staff --> uc4
terminal --> uc5
@enduml
