@startmindmap 系统接口设计
* 称重服务模块
    * 提交称重信息 MQTT/HTTP
    * 获取本次称重结果
* 数据可视化模块
    * 当日各类果实称重量
* 员工信息模块
    * 根据员工卡密钥验证员工信息
    * 根据账号密码登录系统
    * 获取当前登录员工信息
* 农场管理模块
    * 获取农场信息
    * 获取待采摘果实信息
    * 获取采摘批次信息
    * 获取电子秤信息
    * 配置电子秤
@endmindmap