@startmindmap 农业果实称重云端软件
* 农业果实称重云端软件
    * 游客
        * 产品介绍
        * 服务介绍
        * 联系方式
    * 员工
        * 登录认证
        * 查看/修改个人信息
        * 查看历史采摘数据
        * 查看农场基本信息
    * 农场管理员
        * 登录认证
        * 查看/修改个人信息
        * 员工管理
            * 增删改查
            * 权限控制
            * 查看历史采摘数据
        * 电子秤管理
            * 增删改查
            * 实时状态监控和告警
            * 查看历史称重信息
        * 农场管理
            * 增删改查
            * 果实种类管理
            * 采摘批次管理
        * 数据看板
            * 多维度采摘数据可视化
            * 多维度员工数据可视化
            * 数据报表生成和导出
    * 系统管理员
        * 登录认证
        * 查看/修改个人信息
        * 农场管理
            * 审核农场注册申请
            * 查询农场基本信息
        * 服务监控模块
            * 数据库状态监控
            * 物理机状态监控
            * 入口流量监控
    * 电子秤终端(模拟)
        * 激活终端
        * 称重流程
@endmindmap