version: "3"
services:
  # aws-server:

  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    hostname: mysql-server
    networks:
      - aws
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=658766@Jzh
      - MYSQL_DATABASE=aws
    volumes:
      - ./.dep/mysql-server/data:/var/lib/mysql
      - ./.dep/mysql-server/conf:/etc/mysql/conf.d

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: "redis-server --requirepass 658766@Jzh"
    volumes:
      - ./.dep/redis/data:/data
networks:
  aws:
    external: true