// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 新增农产品表单
 * @export
 * @interface ProduceAddVo
 */
export interface ProduceAddVo {
    /**
     * 农产品名称
     * @type {string}
     * @memberof ProduceAddVo
     */
    name?: string;
}


