// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 农产品
 * @export
 * @interface ProduceVo
 */
export interface ProduceVo {
    /**
     * 农产品编号
     * @type {number}
     * @memberof ProduceVo
     */
    id?: number;
    /**
     * 农产品名称
     * @type {string}
     * @memberof ProduceVo
     */
    name?: string;
    /**
     * 创建时间
     * @type {number}
     * @memberof ProduceVo
     */
    createTime?: number;
    /**
     * 更新时间
     * @type {number}
     * @memberof ProduceVo
     */
    updateTime?: number;
    /**
     * 状态，0 为未种植，1 为在种植，2 为已删除
     * @type {number}
     * @memberof ProduceVo
     */
    status?: number;
}


