// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 称重记录查询参数
 * @export
 * @interface RecordsGetVo
 */
export interface RecordsGetVo {
    /**
     * 当前页码
     * @type {number}
     * @memberof RecordsGetVo
     */
    page?: number;
    /**
     * 每页记录数
     * @type {number}
     * @memberof RecordsGetVo
     */
    size?: number;
    /**
     * 采摘作业编号
     * @type {number}
     * @memberof RecordsGetVo
     */
    workId?: number;
    /**
     * 员工编号
     * @type {number}
     * @memberof RecordsGetVo
     */
    employeeId?: number;
    /**
     * 电子秤编号
     * @type {number}
     * @memberof RecordsGetVo
     */
    scaleId?: number;
}


