// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 新增称重记录表单
 * @export
 * @interface RecordAddVo
 */
export interface RecordAddVo {
    /**
     * 采摘作业编号
     * @type {number}
     * @memberof RecordAddVo
     */
    workId?: number;
    /**
     * 员工编号
     * @type {number}
     * @memberof RecordAddVo
     */
    employeeId?: number;
    /**
     * 电子秤编号
     * @type {number}
     * @memberof RecordAddVo
     */
    scaleId?: number;
    /**
     * 称重结果
     * @type {number}
     * @memberof RecordAddVo
     */
    dataValue?: number;
    /**
     * 称量结果误差范围，正负多少
     * @type {number}
     * @memberof RecordAddVo
     */
    dataErrorMargin?: number;
    /**
     * 称重单位，0 为 mg，1 为 g，2 为 kg，3 为 t，4 为 lb（磅），5 为 oz（盎司），6 为 ct（克拉
     * @type {number}
     * @memberof RecordAddVo
     */
    unit?: number;
    /**
     * 称重时间，毫秒级时间戳
     * @type {number}
     * @memberof RecordAddVo
     */
    dataTime?: number;
}


