// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 更新电子秤信息表单
 * @export
 * @interface ScaleUpdateVo
 */
export interface ScaleUpdateVo {
    /**
     * 电子秤编号
     * @type {number}
     * @memberof ScaleUpdateVo
     */
    id?: number;
    /**
     * 状态，0 为禁用，1 为启用，2 为已删除
     * @type {number}
     * @memberof ScaleUpdateVo
     */
    status?: number;
}


