// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 新增电子秤信息表单
 * @export
 * @interface ScaleAddVo
 */
export interface ScaleAddVo {
    /**
     * 电子秤密钥
     * @type {string}
     * @memberof ScaleAddVo
     */
    skey?: string;
    /**
     * 型号
     * @type {string}
     * @memberof ScaleAddVo
     */
    model?: string;
    /**
     * 最大量程
     * @type {number}
     * @memberof ScaleAddVo
     */
    maxCapacity?: number;
    /**
     * 最小量程
     * @type {number}
     * @memberof ScaleAddVo
     */
    minCapacity?: number;
    /**
     * 量程单位，0 为 mg，1 为 g，2 为 kg，3 为 t，4 为 lb（磅），5 为 oz（盎司），6 为 ct（克拉）
     * @type {number}
     * @memberof ScaleAddVo
     */
    unit?: number;
    /**
     * 检定分度值
     * @type {number}
     * @memberof ScaleAddVo
     */
    verificationInterval?: number;
    /**
     * 显示分度值
     * @type {number}
     * @memberof ScaleAddVo
     */
    displayInterval?: number;
    /**
     * 分度值单位，0 为 mg，1 为 g，2 为 kg，3 为 t，4 为 lb（磅），5 为 oz（盎司），6 为 ct（克拉）
     * @type {number}
     * @memberof ScaleAddVo
     */
    unitDv?: number;
    /**
     * 通信协议，0 为 MQTT，1 为 HTTP
     * @type {number}
     * @memberof ScaleAddVo
     */
    protocol?: number;
}


