// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 更新个人信息表单
 * @export
 * @interface UserUpdateMeVo
 */
export interface UserUpdateMeVo {
    /**
     * 用户姓名
     * @type {string}
     * @memberof UserUpdateMeVo
     */
    name?: string;
    /**
     * 密码
     * @type {string}
     * @memberof UserUpdateMeVo
     */
    password?: string;
}


