// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 用户注册表单
 * @export
 * @interface UserRegisterVo
 */
export interface UserRegisterVo {
    /**
     * 用户编号
     * @type {string}
     * @memberof UserRegisterVo
     */
    uid?: string;
    /**
     * 员工姓名
     * @type {string}
     * @memberof UserRegisterVo
     */
    name?: string;
    /**
     * 角色，以英文逗号分隔，比如 ROLE_EMPLOYEE,ROLE_ADMIN
     * @type {string}
     * @memberof UserRegisterVo
     */
    roles?: string;
}


