// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 更新用户信息表单
 * @export
 * @interface UserUpdateVo
 */
export interface UserUpdateVo {
    /**
     * 用户编号
     * @type {string}
     * @memberof UserUpdateVo
     */
    uid?: string;
    /**
     * 用户姓名
     * @type {string}
     * @memberof UserUpdateVo
     */
    name?: string;
    /**
     * 密码
     * @type {string}
     * @memberof UserUpdateVo
     */
    password?: string;
    /**
     * 状态，0 为禁用，1 为启用，2 为已删除
     * @type {number}
     * @memberof UserUpdateVo
     */
    status?: number;
}


