// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 用户登录表单
 * @export
 * @interface UserLoginVo
 */
export interface UserLoginVo {
    /**
     * 用户编号
     * @type {string}
     * @memberof UserLoginVo
     */
    uid?: string;
    /**
     * 密码
     * @type {string}
     * @memberof UserLoginVo
     */
    password?: string;
}


