// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 用户信息
 * @export
 * @interface UserVo
 */
export interface UserVo {
    /**
     * 用户 ID
     * @type {number}
     * @memberof UserVo
     */
    id?: number;
    /**
     * 用户身份证
     * @type {string}
     * @memberof UserVo
     */
    uid?: string;
    /**
     * 员工姓名
     * @type {string}
     * @memberof UserVo
     */
    name?: string;
    /**
     * 角色，以英文逗号分隔，比如 ROLE_EMPLOYEE,ROLE_ADMIN
     * @type {string}
     * @memberof UserVo
     */
    roles?: string;
    /**
     * 创建时间，毫秒级时间戳
     * @type {number}
     * @memberof UserVo
     */
    createTime?: number;
    /**
     * 更新时间，毫秒级时间戳
     * @type {number}
     * @memberof UserVo
     */
    updateTime?: number;
    /**
     * 状态，0 为禁用，1 为启用，2 为已删除
     * @type {number}
     * @memberof UserVo
     */
    status?: number;
}



/**
 * UserListVO, 用户列表
 */
export interface UserListVo {
    count?: number;
    userList?: UserVo[];
    [property: string]: any;
}