// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 作业分配表单
 * @export
 * @interface WorkAssignVo
 */
export interface WorkAssignVo {
    /**
     * 采摘作业编号
     * @type {number}
     * @memberof WorkAssignVo
     */
    workId?: number;
    /**
     * 员工编号列表
     * @type {Array<number>}
     * @memberof WorkAssignVo
     */
    employeeIdList?: Array<number>;
}


