// tslint:disable
/**
 * AWS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkVo
 */
export interface WorkVo {
    /**
     * 
     * @type {number}
     * @memberof WorkVo
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkVo
     */
    produceId?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkVo
     */
    startTime?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkVo
     */
    endTime?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkVo
     */
    dataValue?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkVo
     */
    unit?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkVo
     */
    createTime?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkVo
     */
    updateTime?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkVo
     */
    status?: number;
}


